DROP ALL OBJECTS;

CREATE ALIAS IF NOT EXISTS H2GIS_SPATIAL FOR "org.h2gis.functions.factory.H2GISFunctions.load";
CALL H2GIS_SPATIAL();

CREATE TABLE LOCATION (
	ID INTEGER AUTO_INCREMENT,
	COORDINATES GEOMETRY,
	NAME VARCHAR(200),
	HITS INTEGER
);

INSERT INTO LOCATION (COORDINATES, NAME, HITS) VALUES 
('POINT(37.975627 23.735549)', 'Athens - Syntagma', 0),
('POINT(37.914809 23.705291)', 'Alimos - Marine', 0);